#!/bin/sh
if [ "$#" -ne 3 ]; then
  echo "Usage: pull-request <local branch> <url> <remote branch>"
  exit 1
fi

LOCAL_BRANCH=$1
URL=$2
REMOTE_BRANCH=$3

set -x

git fetch $URL $REMOTE_BRANCH
git branch $LOCAL_BRANCH `git merge-base master FETCH_HEAD`
git checkout $LOCAL_BRANCH
git merge FETCH_HEAD
