#!/bin/sh

while getopts fr opt; do
	case $opt in
		f) FETCH="FETCH";;
		r) REBASE="REBASE";;
	esac
done

ID=${!OPTIND}
LOCAL_BRANCH=pr/$ID

echo Checking out pull request $ID

set -x

if [ "$FETCH" ]; then
	git fetch
fi
git checkout $LOCAL_BRANCH
if [ "$REBASE" ]; then
	git rebase master
fi
